# Generated by Django 5.1.4 on 2025-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("1", "PUBLISH"), ("0", "DRAFT")], default=0, max_length=1
            ),
        ),
    ]
