# Generated by Django 5.1.4 on 2025-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_created_at_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2", "Right"),
                    ("1", "Top"),
                    ("4", "Middle"),
                    ("3", "Left"),
                    ("5", "Footer"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="section",
            field=models.CharField(
                choices=[
                    ("Recent", "Recent"),
                    ("Trending", "Trending"),
                    ("Popular", "Popular"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("1", "PUBLISH"), ("0", "DRAFT")], default=0, max_length=1
            ),
        ),
    ]
