# Generated by Django 5.1.4 on 2025-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_position_alter_post_section_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3", "Left"),
                    ("5", "Footer"),
                    ("4", "Middle"),
                    ("2", "Right"),
                    ("1", "Top"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Recent", "Recent"),
                    ("Popular", "Popular"),
                    ("Trending", "Trending"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("0", "DRAFT"), ("1", "PUBLISH")], default=0, max_length=1
            ),
        ),
    ]
