# Generated by Django 5.1.4 on 2025-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_position_alter_post_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(blank=True, choices=[('3', 'Left'), ('1', 'Top'), ('4', 'Middle'), ('5', 'Footer'), ('2', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(blank=True, choices=[('Trending', 'Trending'), ('Recent', 'Recent'), ('Popular', 'Popular')], max_length=100, null=True),
        ),
    ]
